import React, {useState, useEffect} from 'react'
import {XMarkIcon} from "@heroicons/react/24/solid";

export default function Disclaimer() {
    const [show, setShow] = useState(false)

    useEffect(() => {
        // Check if user has closed it before
        const hasClosed = localStorage.getItem("disclaimer_closed")

        if (!hasClosed) {
            setShow(true)
        }
    }, [])

    const handleHide = () => {
        // Save user action so it won't show again
        localStorage.setItem("disclaimer_closed", "true")
        setShow(false)
    }

    if (!show) return null

    return (
        <div className="bg-blue-50 p-3 rounded-md">
            <div className="flex flex-row justify-between items-center">
                <p className="font-semibold text-lg text-blue-800 mb-1">
                    DISCLAIMER !!!
                </p>
                <button onClick={handleHide}>
                    <XMarkIcon className="w-7 h-7 text-red-500" />
                </button>
            </div>

            <p className="text-blue-700 whitespace-pre-wrap">
                Disclaimer: This content was generated by AI based on the materials provided and may not represent complete or official information.
            </p>
        </div>
    )
}

export  function CopyRight() {
    const [show, setShow] = useState(false)

    useEffect(() => {

        const hasClosed = localStorage.getItem("copy_right")

        if (!hasClosed) {
            setShow(true)
        }
    }, [])

    const handleHide = () => {
        // Save user action so it won't show again
        localStorage.setItem("copy_right", "true")
        setShow(false)
    }

    if (!show) return null

    return (
        <div className="bg-red-50 p-3 rounded-md">
            <div className="flex flex-row justify-between items-center">
                <p className="font-semibold text-sm text-red-800 mb-1">
                    COPYRIGHT NOTICE !!!
                </p>
                <button onClick={handleHide}>
                    <XMarkIcon className="w-7 h-7 text-red-500" />
                </button>
            </div>

            <p className="text-red-700 text-xs whitespace-pre-wrap">
               Notice: Documents are student-uploaded for educational purpose. If your work appears here without permission, please report it for takedown.
            </p>
        </div>
    )
}

